### ISSUE TITLE
Cast error when converting string to float in get_cpu_percent_linux. 

### ISSUE THREAD

**Issue by luciabouzaheguerte** [sb-ai-lab/Eco2AI#6]
Hi, i got this error when running the tool (version 0.3.5): 

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/96236370/218391349-d2abdc11-d156-4e39-873d-9ee9fbe2503a.png">

when running top command, it shows me the values with commas:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/96236370/218391723-92365770-55ab-4df9-aa33-ca121f2ddebc.png">

**Desktop**

<img width="916" alt="image" src="https://user-images.githubusercontent.com/96236370/218392081-441e36ee-9a52-49b0-a239-7c03f44e8400.png">

To fix it, i changed line 533 of eco2ai/tools/tools_cpu.py:

from: sum_cpu += float(words[8])
to: sum_cpu += float(words[8].replace(",","."))

Can you add this to the repo? thanks!
Lucía

**Comment by alexnkorovin** [comment]
Thank you for your comment. Your fix has been implemented. You can get the update of eco2AI from PyPi
